(cl:defpackage acsi_drone-srv
  (:use )
  (:export
   "INTERPOLATETRAJECTORY"
   "<INTERPOLATETRAJECTORY-REQUEST>"
   "INTERPOLATETRAJECTORY-REQUEST"
   "<INTERPOLATETRAJECTORY-RESPONSE>"
   "INTERPOLATETRAJECTORY-RESPONSE"
   "READCSV"
   "<READCSV-REQUEST>"
   "READCSV-REQUEST"
   "<READCSV-RESPONSE>"
   "READCSV-RESPONSE"
  ))

