// Generated by gencpp from file acsi_drone/interpolateTrajectory.msg
// DO NOT EDIT!


#ifndef ACSI_DRONE_MESSAGE_INTERPOLATETRAJECTORY_H
#define ACSI_DRONE_MESSAGE_INTERPOLATETRAJECTORY_H

#include <ros/service_traits.h>


#include <acsi_drone/interpolateTrajectoryRequest.h>
#include <acsi_drone/interpolateTrajectoryResponse.h>


namespace acsi_drone
{

struct interpolateTrajectory
{

typedef interpolateTrajectoryRequest Request;
typedef interpolateTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct interpolateTrajectory
} // namespace acsi_drone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::acsi_drone::interpolateTrajectory > {
  static const char* value()
  {
    return "08c65d36e588352eeb9023eb41c1137c";
  }

  static const char* value(const ::acsi_drone::interpolateTrajectory&) { return value(); }
};

template<>
struct DataType< ::acsi_drone::interpolateTrajectory > {
  static const char* value()
  {
    return "acsi_drone/interpolateTrajectory";
  }

  static const char* value(const ::acsi_drone::interpolateTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::acsi_drone::interpolateTrajectoryRequest> should match 
// service_traits::MD5Sum< ::acsi_drone::interpolateTrajectory > 
template<>
struct MD5Sum< ::acsi_drone::interpolateTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::acsi_drone::interpolateTrajectory >::value();
  }
  static const char* value(const ::acsi_drone::interpolateTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::acsi_drone::interpolateTrajectoryRequest> should match 
// service_traits::DataType< ::acsi_drone::interpolateTrajectory > 
template<>
struct DataType< ::acsi_drone::interpolateTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::acsi_drone::interpolateTrajectory >::value();
  }
  static const char* value(const ::acsi_drone::interpolateTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::acsi_drone::interpolateTrajectoryResponse> should match 
// service_traits::MD5Sum< ::acsi_drone::interpolateTrajectory > 
template<>
struct MD5Sum< ::acsi_drone::interpolateTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::acsi_drone::interpolateTrajectory >::value();
  }
  static const char* value(const ::acsi_drone::interpolateTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::acsi_drone::interpolateTrajectoryResponse> should match 
// service_traits::DataType< ::acsi_drone::interpolateTrajectory > 
template<>
struct DataType< ::acsi_drone::interpolateTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::acsi_drone::interpolateTrajectory >::value();
  }
  static const char* value(const ::acsi_drone::interpolateTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACSI_DRONE_MESSAGE_INTERPOLATETRAJECTORY_H
