// Generated by gencpp from file acsi_drone/readCSV.msg
// DO NOT EDIT!


#ifndef ACSI_DRONE_MESSAGE_READCSV_H
#define ACSI_DRONE_MESSAGE_READCSV_H

#include <ros/service_traits.h>


#include <acsi_drone/readCSVRequest.h>
#include <acsi_drone/readCSVResponse.h>


namespace acsi_drone
{

struct readCSV
{

typedef readCSVRequest Request;
typedef readCSVResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct readCSV
} // namespace acsi_drone


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::acsi_drone::readCSV > {
  static const char* value()
  {
    return "6a2d01face071aecad4ab5f349e87b14";
  }

  static const char* value(const ::acsi_drone::readCSV&) { return value(); }
};

template<>
struct DataType< ::acsi_drone::readCSV > {
  static const char* value()
  {
    return "acsi_drone/readCSV";
  }

  static const char* value(const ::acsi_drone::readCSV&) { return value(); }
};


// service_traits::MD5Sum< ::acsi_drone::readCSVRequest> should match 
// service_traits::MD5Sum< ::acsi_drone::readCSV > 
template<>
struct MD5Sum< ::acsi_drone::readCSVRequest>
{
  static const char* value()
  {
    return MD5Sum< ::acsi_drone::readCSV >::value();
  }
  static const char* value(const ::acsi_drone::readCSVRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::acsi_drone::readCSVRequest> should match 
// service_traits::DataType< ::acsi_drone::readCSV > 
template<>
struct DataType< ::acsi_drone::readCSVRequest>
{
  static const char* value()
  {
    return DataType< ::acsi_drone::readCSV >::value();
  }
  static const char* value(const ::acsi_drone::readCSVRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::acsi_drone::readCSVResponse> should match 
// service_traits::MD5Sum< ::acsi_drone::readCSV > 
template<>
struct MD5Sum< ::acsi_drone::readCSVResponse>
{
  static const char* value()
  {
    return MD5Sum< ::acsi_drone::readCSV >::value();
  }
  static const char* value(const ::acsi_drone::readCSVResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::acsi_drone::readCSVResponse> should match 
// service_traits::DataType< ::acsi_drone::readCSV > 
template<>
struct DataType< ::acsi_drone::readCSVResponse>
{
  static const char* value()
  {
    return DataType< ::acsi_drone::readCSV >::value();
  }
  static const char* value(const ::acsi_drone::readCSVResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACSI_DRONE_MESSAGE_READCSV_H
