// Generated by gencpp from file acsi_drone/readCSVResponse.msg
// DO NOT EDIT!


#ifndef ACSI_DRONE_MESSAGE_READCSVRESPONSE_H
#define ACSI_DRONE_MESSAGE_READCSVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace acsi_drone
{
template <class ContainerAllocator>
struct readCSVResponse_
{
  typedef readCSVResponse_<ContainerAllocator> Type;

  readCSVResponse_()
    : waypoints()  {
    }
  readCSVResponse_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::acsi_drone::readCSVResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acsi_drone::readCSVResponse_<ContainerAllocator> const> ConstPtr;

}; // struct readCSVResponse_

typedef ::acsi_drone::readCSVResponse_<std::allocator<void> > readCSVResponse;

typedef boost::shared_ptr< ::acsi_drone::readCSVResponse > readCSVResponsePtr;
typedef boost::shared_ptr< ::acsi_drone::readCSVResponse const> readCSVResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acsi_drone::readCSVResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acsi_drone::readCSVResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace acsi_drone

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'acsi_drone': ['/home/cerlabcontrol/Desktop/Drone Rewrite/src/acsi_drone/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::acsi_drone::readCSVResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acsi_drone::readCSVResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acsi_drone::readCSVResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acsi_drone::readCSVResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acsi_drone::readCSVResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acsi_drone::readCSVResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acsi_drone::readCSVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea70e23febd08605663de4b49bc50398";
  }

  static const char* value(const ::acsi_drone::readCSVResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea70e23febd08605ULL;
  static const uint64_t static_value2 = 0x663de4b49bc50398ULL;
};

template<class ContainerAllocator>
struct DataType< ::acsi_drone::readCSVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acsi_drone/readCSVResponse";
  }

  static const char* value(const ::acsi_drone::readCSVResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acsi_drone::readCSVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray waypoints\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::acsi_drone::readCSVResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acsi_drone::readCSVResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct readCSVResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acsi_drone::readCSVResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acsi_drone::readCSVResponse_<ContainerAllocator>& v)
  {
    s << indent << "waypoints: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACSI_DRONE_MESSAGE_READCSVRESPONSE_H
